In [241]:
import numpy as np
import pandas as pd

In [242]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [243]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [244]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [199]:
movies = movies.merge(credits,on='title')

In [200]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [201]:
#colums which can make tags
#genres
#id
#keywords
#title
#overview
#cast
#crew

movies[['movie_id','title','genres','overview','keywords','cast','crew']]

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",El Mariachi just wants to play his guitar and ...,"[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",A newlywed couple's honeymoon is upended by th...,[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,[],When ambitious New York attorney Sam is sent t...,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]",Ever since the second grade when he first saw ...,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [202]:
movies =movies[['movie_id','title','genres','overview','keywords','cast','crew']]

In [203]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [204]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   genres    4809 non-null   object
 3   overview  4806 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [205]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
overview    3
keywords    0
cast        0
crew        0
dtype: int64

In [206]:
movies.dropna(inplace=True)

In [207]:
movies.duplicated().sum()

0

In [208]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [209]:
#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

# action adventure fantasy science fiction

In [210]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [211]:
movies['genres']=movies['genres'].apply(convert)

In [212]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [213]:
movies['keywords'] = movies['keywords'].apply(convert)

In [214]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [215]:
def convert3(obj):
    l=[]
    for i in ast.literal_eval(obj):
        counter=0
        if counter !=3:
            l.append(i['name'])
            counter=counter+1
        else:
            break
    return l

In [216]:
 movies['cast']= movies['cast'].apply(convert3)

In [217]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [218]:
import ast
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [219]:
movies['crew']=movies['crew'].apply(fetch_director)

In [220]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [221]:
movies['overview']=movies['overview'].apply(lambda x: x.split())

In [222]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [223]:
movies['genres']=movies['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x: [i.replace(" ","") for i in x])

In [224]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [225]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [226]:
new_df=movies[['movie_id','title','tags']]

In [227]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [228]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\PRANAT~1.IND\AppData\Local\Temp/ipykernel_580/487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [229]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [230]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\PRANAT~1.IND\AppData\Local\Temp/ipykernel_580/4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [231]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [232]:
import nltk

In [233]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [234]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i));
    return " ".join(y)

In [235]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\PRANAT~1.IND\AppData\Local\Temp/ipykernel_580/3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [236]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron'

In [237]:
new_df['tags'][1]

"captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems. adventur fantasi action ocean drugabus exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditssting johnnydepp orlandobloom keiraknightley stellanskarsgård chowyun-fat billnighi geoffreyrush jackdavenport kevinmcn tomholland naomieharri jonathanpryc keithrichard leearenberg mackenziecrook gregelli davidbaili martinklebba davidschofield laurenmah vanessabranch angusbarnett gilesnew reggiele dominicscottkay takayofisch davidmeuni ho-kwants andybeckwith peterdonaldbadalamentiii christophers.capp keithrichard hakeemkae-kazim ghassanmassoud goreverbinski"

In [238]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(new_df['tags']).toarray()

In [239]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [240]:
vectors[32]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [246]:
from sklearn.metrics.pairwise import cosine_similarity

In [248]:
similarity=cosine_similarity(vectors)

In [249]:
similarity[999]

array([0.        , 0.        , 0.02344036, ..., 0.03962144, 0.0836242 ,
       0.0438529 ])

In [256]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1216, 0.27028123880866767),
 (582, 0.23162743094465488),
 (2333, 0.22996655275195),
 (3730, 0.22498852128662872),
 (507, 0.22438727760202976)]

In [251]:
sorted(similarity[0],reverse=True)

[1.0000000000000002,
 0.27028123880866767,
 0.23162743094465488,
 0.22996655275195,
 0.22498852128662872,
 0.22438727760202976,
 0.22305671869347438,
 0.22010219462003333,
 0.2175970699446223,
 0.20751433915982237,
 0.20695933859617893,
 0.20691022044226628,
 0.20100756305184242,
 0.19968076595771794,
 0.19790977371009408,
 0.19596237883454903,
 0.19462473604038075,
 0.1938287215142766,
 0.1928473039599675,
 0.1928473039599675,
 0.19145989526687088,
 0.18540496217739155,
 0.18463723646899916,
 0.18281810603178267,
 0.1809806914982567,
 0.1809806914982567,
 0.17837651700316892,
 0.1776672636296754,
 0.175919798853417,
 0.17588161767036212,
 0.17407765595569785,
 0.17407765595569785,
 0.17348855898381338,
 0.17056057308448835,
 0.16898159235484367,
 0.16888013236829963,
 0.16854996561581054,
 0.1682904582015223,
 0.1682904582015223,
 0.16685595311797868,
 0.16351748504193214,
 0.16262312563634837,
 0.160930171455096,
 0.1599005372667078,
 0.1599005372667078,
 0.15909090909090912,
 0.15745916432444343,
 0.15745916432444343,
 0.15731330124142318,
 0.15701373439577193,
 0.15559397856603546,
 0.15392982399673985,
 0.15386436372416595,
 0.15075567228888181,
 0.15075567228888181,
 0.15075567228888181,
 0.1492405014489273,
 0.1492405014489273,
 0.1487044791289829,
 0.1487044791289829,
 0.14782809899727067,
 0.14782809899727067,
 0.14777011582226215,
 0.14716573653773893,
 0.14673479641335554,
 0.1463423517512409,
 0.14625448482542613,
 0.14519080172812554,
 0.14506471329641488,
 0.14484136487558028,
 0.14484136487558028,
 0.1446354779699756,
 0.14245072057454744,
 0.1421338109037403,
 0.14126448280440335,
 0.1411569346481171,
 0.1399731277389636,
 0.13977653617040256,
 0.13762047064079508,
 0.1374416265488099,
 0.13623731522826651,
 0.13483997249264842,
 0.13483997249264842,
 0.13483997249264842,
 0.13402192668680965,
 0.1340050420345616,
 0.13336626734231613,
 0.13336626734231613,
 0.13336626734231613,
 0.1332504477222565,
 0.1315903389919538,
 0.1315903389919538,
 0.1315903389919538,
 0.1305582419667734,
 0.1305582419667734,
 0.13005121775247103,
 0.1292719224987548,
 0.1292719224987548,
 0.12921914767618442,
 0.12921914767618442,
 0.1292191476761844,
 0.12892415701965754,
 0.128564869306645,
 0.12792042981336627,
 0.12792042981336627,
 0.12741179785940637,
 0.12741179785940637,
 0.1266600992762247,
 0.1257389226923863,
 0.1257389226923863,
 0.1257389226923863,
 0.1256297269074015,
 0.12543630150106364,
 0.12436708454077278,
 0.12424730498438732,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12392039927415242,
 0.12351231781710247,
 0.12309149097933275,
 0.12309149097933275,
 0.12227899701112964,
 0.12227899701112963,
 0.12227899701112963,
 0.12196734422726127,
 0.12196734422726127,
 0.12196734422726126,
 0.12087344460380703,
 0.1207011373963169,
 0.1207011373963169,
 0.1207011373963169,
 0.12060453783110546,
 0.12060453783110546,
 0.11980845957463077,
 0.11918282365569904,
 0.11918282365569904,
 0.11918282365569904,
 0.11826247919781653,
 0.11826247919781653,
 0.11776030079682895,
 0.11776030079682895,
 0.11776030079682895,
 0.11772040233700279,
 0.11725441178024137,
 0.11631052629980887,
 0.11631052629980886,
 0.1160517706371319,
 0.11495012246792571,
 0.11495012246792571,
 0.11487593716012254,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11306675421666137,
 0.11306675421666137,
 0.11306675421666137,
 0.11306675421666137,
 0.11306675421666137,
 0.11306675421666136,
 0.11306675421666136,
 0.11236664374387369,
 0.11236664374387369,
 0.11236664374387369,
 0.11236664374387369,
 0.11197850219117086,
 0.11197850219117086,
 0.11197850219117086,
 0.11113855611859677,
 0.11113855611859677,
 0.11113855611859677,
 0.11009637651263605,
 0.11009637651263605,
 0.11009637651263605,
 0.10994987428338562,
 0.1096908636190696,
 0.1096908636190696,
 0.10889310129609417,
 0.10879853497231115,
 0.10830607221477648,
 0.10770505460691618,
 0.107682623063487,
 0.107682623063487,
 0.107682623063487,
 0.107682623063487,
 0.10726454129012915,
 0.10660035817780522,
 0.10660035817780522,
 0.10660035817780522,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10586770098608783,
 0.10497277621629561,
 0.10497277621629561,
 0.10497277621629561,
 0.10497277621629561,
 0.10497277621629561,
 0.10453025125088636,
 0.1044465935734187,
 0.10444659357341869,
 0.1037571695799112,
 0.10353942082032278,
 0.10353942082032278,
 0.10353942082032278,
 0.10353942082032278,
 0.10353942082032278,
 0.10353942082032278,
 0.10341753799900383,
 0.10341753799900383,
 0.10341753799900383,
 0.10257624248277727,
 0.10257624248277727,
 0.1019294382875251,
 0.1019294382875251,
 0.1019294382875251,
 0.10176802973291377,
 0.10163945352271772,
 0.10154529930749041,
 0.10112997936948631,
 0.10112997936948631,
 0.10112997936948631,
 0.10072787050317253,
 0.10072787050317253,
 0.10072787050317253,
 0.10072787050317253,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.09988907373180403,
 0.09988907373180403,
 0.09984038297885897,
 0.09928550884822428,
 0.09927330486454494,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09897594780811197,
 0.09897594780811197,
 0.09883693657685838,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09813358399735746,
 0.09813358399735746,
 0.09813358399735746,
 0.09813358399735746,
 0.09811049102515929,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.0978231976089037,
 0.09731236802019037,
 0.09656090991705352,
 0.09656090991705352,
 0.09656090991705352,
 0.09656090991705352,
 0.09656090991705352,
 0.09651142956027287,
 0.09651142956027287,
 0.09651142956027287,
 0.09642365197998373,
 0.09642365197998373,
 0.09642365197998373,
 0.09642365197998373,
 0.09642365197998373,
 0.09642365197998373,
 0.09572994763343545,
 0.09534625892455924,
 0.09534625892455924,
 0.09534625892455924,
 0.09496714704969828,
 0.09496714704969828,
 0.09430419201928972,
 0.09430419201928972,
 0.09430419201928972,
 0.09430419201928972,
 0.09422229518055114,
 0.09422229518055114,
 0.09422229518055114,
 0.09422229518055114,
 0.09422229518055114,
 0.09417632186960223,
 0.09417632186960223,
 0.09417632186960223,
 0.09417632186960223,
 0.09417632186960223,
 0.09349469900084573,
 0.09304842103984709,
 0.09304842103984709,
 0.09304842103984709,
 0.09304842103984709,
 0.09231861823449956,
 0.09231861823449956,
 0.09208868358546966,
 0.09208868358546966,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09196009797434057,
 0.09090909090909091,
 0.09090909090909091,
 0.09090909090909091,
 0.09090909090909091,
 0.09090909090909091,
 0.09045340337332909,
 0.09045340337332909,
 0.09009374626955591,
 0.09009374626955591,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08945703337056415,
 0.08945703337056415,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.0888336318148377,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.0886968593983624,
 0.08822308415507318,
 0.0879598994267085,
 0.0879598994267085,
 0.0879598994267085,
 0.0879598994267085,
 0.0879598994267085,
 0.0876249546540977,
 0.0876249546540977,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08646430798325933,
 0.0861460984507896,
 0.0861460984507896,
 0.0861460984507896,
 0.0861460984507896,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08534859274986485,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.0848066914440948,
 0.0844400661841498,
 0.0844400661841498,
 0.0844400661841498,
 0.0844400661841498,
 0.0844400661841498,
 0.08427498280790527,
 0.08427498280790527,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08398387664337814,
 0.08375315127160099,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08283153665625823,
 0.08283153665625823,
 0.08283153665625823,
 0.0827379240401869,
 0.08257228238447704,
 0.08257228238447704,
 0.08257228238447704,
 0.08257228238447704,
 0.08257228238447704,
 0.08215419219227854,
 0.08206099398622183,
 0.08206099398622183,
 0.08206099398622183,
 0.08175874252096607,
 0.08131156281817417,
 0.08131156281817417,
 0.08131156281817417,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08122955416108235,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08058229640253803,
 0.08026441628216505,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.0799502686333539,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07987230638308718,
 0.07918075824648958,
 0.07918075824648958,
 0.07901744265512675,
 0.0787295821622217,
 0.0787295821622217,
 0.0787295821622217,
 0.0787295821622217,
 0.0787295821622217,
 0.0787295821622217,
 0.07850686719788597,
 0.07850686719788597,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07733602811121826,
 0.07733602811121826,
 0.07720914364821829,
 0.07720914364821829,
 0.07658395810674837,
 0.07653459686532839,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07644707871564382,
 0.07597371763975862,
 0.07597371763975862,
 0.07597371763975862,
 0.07597371763975862,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07500375028127344,
 0.07479575920067658,
 0.07460470969529907,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07422696190252054,
 0.07422696190252054,
 0.07367094686837573,
 0.07367094686837573,
 0.07367094686837573,
 0.07367094686837573,
 0.07367094686837573,
 0.07367094686837573,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667779,
 0.07336739820667777,
 0.07312724241271307,
 0.07312724241271307,
 0.07312724241271307,
 0.07259540086406277,
 0.07259540086406277,
 0.07259540086406277,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07242068243779014,
 0.07207499701564472,
 0.07207499701564472,
 0.07207499701564471,
 0.07156562669645132,
 0.07156562669645132,
 0.07156562669645132,
 0.07156562669645132,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07150969419341943,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07106690545187015,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07063224140220167,
 0.07057846732405855,
 0.07057846732405855,
 0.07029019463944167,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06978631577988531,
 0.06963106238227913,
 0.06963106238227913,
 0.06963106238227913,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06897007348075543,
 0.06872081327440495,
 0.06872081327440495,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06818181818181818,
 0.06784535315527584,
 0.06784535315527584,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06668313367115807,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06668313367115805,
 0.06619033923214952,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.06596992457003137,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.0652791209833867,
 0.06502560887623551,
 0.06465081838352359,
 0.06460957383809221,
 0.06460957383809221,
 0.06460957383809221,
 0.06460957383809221,
 0.06460957383809221,
 0.06460957383809221,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06428243465332249,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06333004963811235,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.06286946134619315,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.0627181507505318,
 0.062197041357112286,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.06212365249219367,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.061545745489666376,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06154574548966637,
 0.06122767749226271,
 0.06098367211363063,
 0.06098367211363063,
 0.06098367211363063,
 0.06098367211363063,
 0.06098367211363063,
 0.06098367211363063,
 0.06091449038731726,
 0.06054493496206034,
 0.06043672230190352,
 0.06043672230190352,
 0.06043672230190352,
 0.06043672230190352,
 0.06043672230190352,
 0.06043672230190352,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.060003000225018754,
 0.05990422978731538,
 0.05990422978731538,
 0.05990422978731538,
 0.05990422978731538,
 0.05990422978731538,
 0.05990422978731538,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.05938556868486719,
 0.059385568684867183,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.059131239598908265,
 0.058880150398414474,

In [261]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [262]:
recommend('Avatar')

Aliens vs Predator: Requiem
Battle: Los Angeles
Predator
Falcon Rising
Independence Day